### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by dev-sngwn** [chahuja/language2pose#1]
This command
`python render.py -dataset KITMocap -path2data ../dataset/kit-mocap/new_fke -feats_kind fke`

Throws this error:
...
3422 ../dataset/kit-mocap/new_fke/03639_quat.fke
3423 ../dataset/kit-mocap/new_fke/03773_quat.fke
3424 ../dataset/kit-mocap/new_fke/01499_quat.fke
3322 ../dataset/kit-mocap/new_fke/03848_quat.fke
3323 ../dataset/kit-mocap/new_fke/03899_quat.fke
3324 ../dataset/kit-mocap/new_fke/01888_quat.fke
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/my/anaconda3/envs/l2p/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/my/anaconda3/envs/l2p/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/my/Jupyter/temp/language2pose/src/renderUtils.py", line 40, in readNrender
    render(xyz_data, skel, time, output, figsize, description)
  File "/home/my/Jupyter/temp/language2pose/src/data/kit_visualization.py", line 156, in render
    suptitle=description)
  File "/home/my/Jupyter/temp/language2pose/src/utils/visualization.py", line 242, in render_animation
    anim = FuncAnimation(fig, update, frames=np.arange(history*history_offset, num_frames), interval=1000/fps, repeat=False, fargs=init_func(fig, figures, skeleton, figsize, fps))
  File "/home/my/Jupyter/temp/language2pose/src/utils/visualization.py", line 122, in init_func
    draw_offset = int(25/avg_segment_length)
ValueError: cannot convert float NaN to integer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "render.py", line 85, in <module>
    argparseNloop(loop)
  File "/home/my/Jupyter/temp/language2pose/src/argsUtils.py", line 137, in argparseNloop
    loop(args, i)
  File "render.py", line 82, in loop
    parallelRender(filenames, descriptions, outputs, skel, args.feats_kind)
  File "/home/my/Jupyter/temp/language2pose/src/renderUtils.py", line 77, in parallelRender
    parallel(readNrender, zip(filenums, filenames, descriptions, skels, times, outputs, figsizes, feats_kind))
  File "/home/my/Jupyter/temp/language2pose/src/common/parallel.py", line 6, in parallel
    p.map(fn, args)
  File "/home/my/anaconda3/envs/l2p/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/my/anaconda3/envs/l2p/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: cannot convert float NaN to integer

**Comment by WinstonDeng** [comment]
**I fix the issue by this code**

 ```
try:
    draw_offset = int(25/avg_segment_length)
except ValueError:
    draw_offset = 0
```

**Comment by dev-sngwn** [comment]
> **I fix the issue by this code**
> 
> ```
> try:
>    draw_offset = int(25/avg_segment_length)
> except ValueError:
>    draw_offset = 0
> ```

It works, thank you!

**Comment by seyeeet** [comment]
where did you put this?
