### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'args'

### ISSUE THREAD

**Issue by seyeeet** [chahuja/language2pose#19]
why do i get this error :(
```
(torch) Seyeeet@Seyeeet:/media/Seyeeet/Office/language2pose/src$ python dataProcessing/meanVariance.py -mask '[0]' -feats_kind rifke -dataset KITMocap -path2data /media/Seyeeet/Office/language2pose/dataset/kit-mocap  -f_new 8
Namespace(angles=[[90]], batch_size=[100], chunks=[1], clean_render=[1], config=[None], cpk=['m'], cuda=[0], curriculum=[0], dataset=['KITMocap'], debug=[0], desc=[None], dev_frac=[0.2], early_stopping=[1], eps=[0], exp=[None], f_new=[8], feats_kind=['rifke'], greedy_save=[1], idx_dependent=[1], kl_anneal=[0], lmksSubset=[['all']], load=[None], lossKwargs=[[{'reduction': 'sum'}]], losses=[['MSELoss']], lr=[0.001], mask=[[0]], model=['Autoencoder'], modelKwargs=[{'num_channels_list': [40, 40, 20]}], num_epochs=[50], offset=[0], overfit=[0], path2data=['/media/Seyeeet/Office/language2pose/dataset/kit-mocap'], pose_mask=[0], render=['inf'], render_list=[None], s2v=[0], save_dir=['save/model'], save_model=[1], script=[None], seed=[11212], seedLength=[20], stop_thresh=[3], tb=[0], time=[32], train_frac=[0.6], transforms=[['zNorm']], view=['sentences.txt'])
[]
Namespace(angles=[90], batch_size=100, chunks=1, clean_render=1, config=None, cpk='m', cuda=0, curriculum=0, dataset='KITMocap', debug=0, desc=None, dev_frac=0.2, early_stopping=1, eps=0, exp=None, f_new=8, feats_kind='rifke', greedy_save=1, idx_dependent=1, kl_anneal=0, lmksSubset=['all'], load=None, lossKwargs=[{'reduction': 'sum'}], losses=['MSELoss'], lr=0.001, mask=[0], model='Autoencoder', modelKwargs={'num_channels_list': [40, 40, 20]}, num_epochs=50, offset=0, overfit=0, path2data='/media/Seyeeet/Office/language2pose/dataset/kit-mocap', pose_mask=0, render='inf', render_list=None, s2v=0, save_dir='save/model', save_model=1, script=None, seed=11212, seedLength=20, stop_thresh=3, tb=0, time=32, train_frac=0.6, transforms=['zNorm'], view='sentences.txt')
Traceback (most recent call last):
  File "dataProcessing/meanVariance.py", line 96, in <module>
    argparseNloop(loop)
  File "/media/Seyeeet/Office/language2pose/src/argsUtils.py", line 137, in argparseNloop
    loop(args, i)
  File "dataProcessing/meanVariance.py", line 27, in loop
    BookKeeper._set_seed(args)
  File "/media/Seyeeet/Office/language2pose/src/pycasper/BookKeeper.py", line 154, in _set_seed
    random.seed(self.args.seed)
AttributeError: 'Namespace' object has no attribute 'args'
(torch) Seyeeet@Seyeeet:/media/Seyeeet/Office/language2pose/src$ 

```

**Comment by seyeeet** [comment]
i think I solved it by changing 
`def _set_seed(self):`


to 
```
def _set_seed(inputarg):
    ## seed numpy and torch
    random.seed(inputarg.seed)
    np.random.seed(inputarg.seed)
    torch.manual_seed(inputarg.seed)
    torch.cuda.manual_seed_all(inputarg.seed)
    torch.cuda.manual_seed(inputarg.seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    os.environ['PYTHONHASHSEED'] = str(inputarg.seed)
```

**Comment by Kerry-zzx** [comment]
change self.args.seed to self.seed
