### ISSUE TITLE
AssertionError: Rotation invariant Forward Kinematics have 3 parameters for root joint

### ISSUE THREAD

**Issue by WinstonDeng** [chahuja/language2pose#3]
When I run  **Calculating mean+variance for Z-Normalization**:

> python dataProcessing/meanVariance.py -mask '[0]' -feats_kind rifke -dataset KITMocap -path2data ../dataset/kit-mocap -f_new 8

Error:

> Traceback (most recent call last):
  File "dataProcessing/meanVariance.py", line 96, in <module>
    argparseNloop(loop)
  File "F:\Speech2Gesture\language2pose\src\argsUtils.py", line 137, in argparseNloop
    loop(args, i)
  File "dataProcessing/meanVariance.py", line 47, in loop
    f_new=f_new)
  File "F:\Speech2Gesture\language2pose\src\dataUtils.py", line 37, in __init__
    assert len(mask) == 1, 'Rotation invariant Forward Kinematics have 3 parameters for root joint'
AssertionError: Rotation invariant Forward Kinematics have 3 parameters for root joint

So that I print len(mask):

> len(mask)=3

**How to address it?**

**Comment by WinstonDeng** [comment]
This error only occurs in PyCharm due to some unknown reasons. It'ok in VSCode.
