### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape' when rendering the ground truths 

### ISSUE THREAD

**Issue by lexical-kenobi** [chahuja/language2pose#6]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hanSolo/anaconda3/envs/test-torch/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/hanSolo/anaconda3/envs/test-torch/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/renderUtils.py", line 40, in readNrender
    render(xyz_data, skel, time, output, figsize, description)
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/data/kit_visualization.py", line 156, in render
    suptitle=description)
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/utils/visualization.py", line 288, in render_animation
    anim.save(output, writer=writer)
  File "/home/hanSolo/anaconda3/envs/test-torch/lib/python3.7/site-packages/matplotlib/animation.py", line 1141, in save
    anim._draw_next_frame(d, blit=False)
  File "/home/hanSolo/anaconda3/envs/test-torch/lib/python3.7/site-packages/matplotlib/animation.py", line 1176, in _draw_next_frame
    self._draw_frame(framedata)
  File "/home/hanSolo/anaconda3/envs/test-torch/lib/python3.7/site-packages/matplotlib/animation.py", line 1726, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/utils/visualization.py", line 207, in update
    liness[fig_num][count][hist][i-1][0].set_3d_properties([positions_world[count][hist][i, z], positions_world[count][hist][skeleton_parents[i], z]], zdir='y')
  File "/home/hanSolo/anaconda3/envs/test-torch/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py", line 143, in set_3d_properties
    zs = np.broadcast_to(zs, xs.shape)
AttributeError: 'list' object has no attribute 'shape'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "render.py", line 85, in <module>
    argparseNloop(loop)
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/argsUtils.py", line 137, in argparseNloop
    loop(args, i)
  File "render.py", line 82, in loop
    parallelRender(filenames, descriptions, outputs, skel, args.feats_kind)
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/renderUtils.py", line 77, in parallelRender
    parallel(readNrender, zip(filenums, filenames, descriptions, skels, times, outputs, figsizes, feats_kind))
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/common/parallel.py", line 6, in parallel
    p.map(fn, args)
  File "/home/hanSolo/anaconda3/envs/test-torch/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/hanSolo/anaconda3/envs/test-torch/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'list' object has no attribute 'shape'

**Comment by chahuja** [comment]
Hmm, I am not sure what is causing this error, or if this error is for all files. 

Try replacing `parallel(readNrender, zip(filenums, filenames, descriptions, skels, times, outputs, figsizes, feats_kind))` with `readNrender(filenums[i], filenames[i], descriptions[i], skels[i], times[i], outputs[i], figsizes[i], feats_kind[i])` for some random values of `i`. This would help verify if this function is failing for one or possibly all files.
