### ISSUE TITLE
When running render.py matplotlib showing errors

### ISSUE THREAD

**Issue by lexical-kenobi** [chahuja/language2pose#8]
Traceback (most recent call last):
  File "render.py", line 4, in <module>
    from dataUtils import *
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/dataUtils.py", line 5, in <module>
    from data.data import *
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/data/data.py", line 18, in <module>
    from utils.visualization import *
  File "/mnt/D4567C46567C2AFE/Work HDD/Research/test/language2pose/src/utils/visualization.py", line 13, in <module>
    from matplotlib.animation import FuncAnimation, writers
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/site-packages/matplotlib/animation.py", line 737, in <module>
    class ImageMagickWriter(ImageMagickBase, MovieWriter):
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/site-packages/matplotlib/animation.py", line 120, in wrapper
    if writerClass.isAvailable():
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/site-packages/matplotlib/animation.py", line 730, in isAvailable
    return super().isAvailable()
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/site-packages/matplotlib/animation.py", line 427, in isAvailable
    return shutil.which(cls.bin_path()) is not None
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/site-packages/matplotlib/animation.py", line 724, in bin_path
    binpath = mpl._get_executable_info('magick').executable
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/site-packages/matplotlib/__init__.py", line 384, in _get_executable_info
    return impl([path, "--version"], r"^Version: ImageMagick (\S*)")
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/site-packages/matplotlib/__init__.py", line 324, in impl
    args, stderr=subprocess.STDOUT, universal_newlines=True)
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/hanSolo/anaconda3/envs/torch/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'convert'

**Comment by chahuja** [comment]
It seems that you do not have [imagemagick](https://imagemagick.org/script/index.php) installed. Try running `convert --help` in the command line to verify if it is installed or not.
